// Reserved paths that cannot be used as handles. Also profanity banlist entry-point.
// At M5, add the Shutterstock profanity list here via a build step that pulls the JSON.
const RESERVED = new Set([
  'about',
  'admin',
  'api',
  'articles',
  'auth',
  'blog',
  'bookmarks',
  'compose',
  'docs',
  'explore',
  'favicon.ico',
  'feed',
  'hashtag',
  'hashtags',
  'home',
  'help',
  'inbox',
  'login',
  'logout',
  'mentions',
  'messages',
  'moderation',
  'notifications',
  'policy',
  'privacy',
  'profile',
  'r',
  'robots.txt',
  'search',
  'settings',
  'signin',
  'signup',
  'sitemap.xml',
  'staff',
  'status',
  'support',
  'tags',
  'terms',
  'transparency',
  'twotter',
  'u',
  'user',
  'users',
  'verified',
  'ws',
])

export function isReservedHandle(handle: string): boolean {
  return RESERVED.has(handle.toLowerCase())
}
